# Site settings
title: Guidebook Engineering
email: engineering@domain.com
description: Guidebook's engineering blog
baseurl: ""
url: "https://engineering.guidebook.com" # the base hostname & protocol for your site
twitter_username: guidebook
github_username:  guidebook
excerpt_separator: <!--end-->
guidebookbaseurl: "https://guidebook.com"

env: "prod"

exclude: [bower_components, node_modules, _sass, _js, .git, .sass-cache, Gemfile, Gemfile.lock, gulpfile.js, compass-config.rb]

# Build settings
markdown: kramdown

#dev blog
permalink: pretty
tag_page_layout: category
tag_page_dir: category

#mini bundler
minibundle:
  minifier_commands:
    css: ./node_modules/.bin/uglifycss
    js: ./node_modules/.bin/uglifyjs
